/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Cadastro;

import Controller.Cadastro.CadastroServicoController;
import Model.DAO.Banco;
import javax.swing.JTextField;

/**
 *
 * @author tayen
 */
public class CadastroServico extends javax.swing.JFrame {

    /**
     * Creates new form CadastroServico
     */
    private final CadastroServicoController controller;
   
    public CadastroServico() {
        initComponents();
        controller = new CadastroServicoController(this);
        Banco.inicia();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltarServicoBotao = new javax.swing.JButton();
        novoServicoPainel = new javax.swing.JPanel();
        novoUsuarioLabel = new javax.swing.JLabel();
        idServicoText = new javax.swing.JTextField();
        descricaoServicoText = new javax.swing.JTextField();
        valorServicoText = new javax.swing.JTextField();
        idServicoLabel = new javax.swing.JLabel();
        descricaoServicoLabel = new javax.swing.JLabel();
        valorServicoLabel1 = new javax.swing.JLabel();
        cadastrarServicoBotao = new javax.swing.JButton();
        telaPrincipalServicoCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 552));
        setPreferredSize(new java.awt.Dimension(915, 555));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltarServicoBotao.setBackground(new java.awt.Color(51, 0, 51));
        voltarServicoBotao.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        voltarServicoBotao.setForeground(new java.awt.Color(255, 153, 255));
        voltarServicoBotao.setText("VOLTAR");
        voltarServicoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarServicoBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(voltarServicoBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 70, 20));

        novoServicoPainel.setBackground(new java.awt.Color(51, 0, 51));
        novoServicoPainel.setForeground(new java.awt.Color(255, 204, 255));
        novoServicoPainel.setToolTipText("");

        novoUsuarioLabel.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        novoUsuarioLabel.setForeground(new java.awt.Color(255, 204, 204));
        novoUsuarioLabel.setText("NOVO SERVIÇO");

        javax.swing.GroupLayout novoServicoPainelLayout = new javax.swing.GroupLayout(novoServicoPainel);
        novoServicoPainel.setLayout(novoServicoPainelLayout);
        novoServicoPainelLayout.setHorizontalGroup(
            novoServicoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(novoServicoPainelLayout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(novoUsuarioLabel)
                .addContainerGap(568, Short.MAX_VALUE))
        );
        novoServicoPainelLayout.setVerticalGroup(
            novoServicoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(novoUsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(novoServicoPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        idServicoText.setBackground(new java.awt.Color(255, 255, 255));
        idServicoText.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        idServicoText.setForeground(new java.awt.Color(102, 0, 102));
        idServicoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idServicoTextActionPerformed(evt);
            }
        });
        getContentPane().add(idServicoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 160, 40));

        descricaoServicoText.setBackground(new java.awt.Color(255, 255, 255));
        descricaoServicoText.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        descricaoServicoText.setForeground(new java.awt.Color(102, 0, 102));
        descricaoServicoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoServicoTextActionPerformed(evt);
            }
        });
        getContentPane().add(descricaoServicoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 370, 40));

        valorServicoText.setBackground(new java.awt.Color(255, 255, 255));
        valorServicoText.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        valorServicoText.setForeground(new java.awt.Color(102, 0, 102));
        valorServicoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorServicoTextActionPerformed(evt);
            }
        });
        getContentPane().add(valorServicoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 190, 40));

        idServicoLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        idServicoLabel.setForeground(new java.awt.Color(51, 0, 51));
        idServicoLabel.setText("Id");
        getContentPane().add(idServicoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 20));

        descricaoServicoLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        descricaoServicoLabel.setForeground(new java.awt.Color(51, 0, 51));
        descricaoServicoLabel.setText("Descrição");
        getContentPane().add(descricaoServicoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, 20));

        valorServicoLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        valorServicoLabel1.setForeground(new java.awt.Color(51, 0, 51));
        valorServicoLabel1.setText("Valor");
        getContentPane().add(valorServicoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, 20));

        cadastrarServicoBotao.setBackground(new java.awt.Color(51, 0, 51));
        cadastrarServicoBotao.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        cadastrarServicoBotao.setForeground(new java.awt.Color(255, 153, 255));
        cadastrarServicoBotao.setText("CADASTRAR");
        cadastrarServicoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarServicoBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarServicoBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 580, 50));

        telaPrincipalServicoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Mary_kay_Menu.png"))); // NOI18N
        telaPrincipalServicoCadastro.setMinimumSize(new java.awt.Dimension(815, 552));
        getContentPane().add(telaPrincipalServicoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarServicoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarServicoBotaoActionPerformed
        controller.voltarParaMenu();
    }//GEN-LAST:event_voltarServicoBotaoActionPerformed

    private void idServicoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idServicoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idServicoTextActionPerformed

    private void descricaoServicoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoServicoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoServicoTextActionPerformed

    private void valorServicoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorServicoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorServicoTextActionPerformed

    private void cadastrarServicoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarServicoBotaoActionPerformed
        controller.cadastrarServico();
    }//GEN-LAST:event_cadastrarServicoBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarServicoBotao;
    private javax.swing.JLabel descricaoServicoLabel;
    private javax.swing.JTextField descricaoServicoText;
    private javax.swing.JLabel idServicoLabel;
    private javax.swing.JTextField idServicoText;
    private javax.swing.JPanel novoServicoPainel;
    private javax.swing.JLabel novoUsuarioLabel;
    private javax.swing.JLabel telaPrincipalServicoCadastro;
    private javax.swing.JLabel valorServicoLabel1;
    private javax.swing.JTextField valorServicoText;
    private javax.swing.JButton voltarServicoBotao;
    // End of variables declaration//GEN-END:variables

    public JTextField getDescricaoServicoText() {
        return descricaoServicoText;
    }

    public void setDescricaoServicoText(JTextField descricaoServicoText) {
        this.descricaoServicoText = descricaoServicoText;
    }

    public JTextField getIdServicoText() {
        return idServicoText;
    }

    public void setIdServicoText(JTextField idServicoText) {
        this.idServicoText = idServicoText;
    }

    public JTextField getValorServicoText() {
        return valorServicoText;
    }

    public void setValorServicoText(JTextField valorServicoText) {
        this.valorServicoText = valorServicoText;
    }

}
