/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Cadastro;

import Controller.Cadastro.CadastroUsuarioController;
import Model.DAO.Banco;
import javax.swing.JComboBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author tayen
 */
public class CadastroUsuario extends javax.swing.JFrame {

    private final CadastroUsuarioController controller;
    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
        this.controller = new CadastroUsuarioController(this);
        Banco.inicia();
         controller.atualizaNivelAcesso();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        novoUsuarioPainel = new javax.swing.JPanel();
        novoUsuarioLabel = new javax.swing.JLabel();
        idUsuarioText = new javax.swing.JTextField();
        nomeUsuarioText = new javax.swing.JTextField();
        sexoUsuarioComboBox = new javax.swing.JComboBox<>();
        dataUsuarioText = new javax.swing.JTextField();
        numeroUsuarioText = new javax.swing.JTextField();
        emailUsuarioText = new javax.swing.JTextField();
        rgUsuarioText = new javax.swing.JTextField();
        senhaUsuarioText = new javax.swing.JPasswordField();
        nivelAcessoUsuarioComboBox = new javax.swing.JComboBox<>();
        cadastrarUsuarioBotao = new javax.swing.JButton();
        voltarUsuarioBotao = new javax.swing.JButton();
        idUsuarioLabel = new javax.swing.JLabel();
        nomeUsuarioLabel = new javax.swing.JLabel();
        sexoUsuarioLabel = new javax.swing.JLabel();
        dataNascimentoUsuarioLabel = new javax.swing.JLabel();
        numeroUsuarioLabel = new javax.swing.JLabel();
        emailUsuarioLabel = new javax.swing.JLabel();
        rgUsuarioLabel = new javax.swing.JLabel();
        senhaUsuarioLabel = new javax.swing.JLabel();
        nivelAcessoUsuarioLabel = new javax.swing.JLabel();
        telaFundoUsuarioCadastro = new javax.swing.JLabel();
        telaPrincipalUsuarioCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(913, 595));
        setPreferredSize(new java.awt.Dimension(913, 552));
        setSize(new java.awt.Dimension(913, 552));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        novoUsuarioPainel.setBackground(new java.awt.Color(51, 0, 51));
        novoUsuarioPainel.setForeground(new java.awt.Color(255, 204, 255));
        novoUsuarioPainel.setToolTipText("");

        novoUsuarioLabel.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        novoUsuarioLabel.setForeground(new java.awt.Color(255, 204, 204));
        novoUsuarioLabel.setText("NOVO USUÁRIO");

        javax.swing.GroupLayout novoUsuarioPainelLayout = new javax.swing.GroupLayout(novoUsuarioPainel);
        novoUsuarioPainel.setLayout(novoUsuarioPainelLayout);
        novoUsuarioPainelLayout.setHorizontalGroup(
            novoUsuarioPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(novoUsuarioPainelLayout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(novoUsuarioLabel)
                .addContainerGap(568, Short.MAX_VALUE))
        );
        novoUsuarioPainelLayout.setVerticalGroup(
            novoUsuarioPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(novoUsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(novoUsuarioPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        idUsuarioText.setBackground(new java.awt.Color(255, 255, 255));
        idUsuarioText.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        idUsuarioText.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(idUsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 100, 30));

        nomeUsuarioText.setBackground(new java.awt.Color(255, 255, 255));
        nomeUsuarioText.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        nomeUsuarioText.setForeground(new java.awt.Color(51, 0, 51));
        nomeUsuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeUsuarioTextActionPerformed(evt);
            }
        });
        getContentPane().add(nomeUsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 500, 30));

        sexoUsuarioComboBox.setBackground(new java.awt.Color(255, 255, 255));
        sexoUsuarioComboBox.setForeground(new java.awt.Color(51, 0, 51));
        sexoUsuarioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        getContentPane().add(sexoUsuarioComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 260, 30));

        dataUsuarioText.setBackground(new java.awt.Color(255, 255, 255));
        dataUsuarioText.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        dataUsuarioText.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(dataUsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 260, 30));

        numeroUsuarioText.setBackground(new java.awt.Color(255, 255, 255));
        numeroUsuarioText.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        numeroUsuarioText.setForeground(new java.awt.Color(51, 0, 51));
        numeroUsuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroUsuarioTextActionPerformed(evt);
            }
        });
        getContentPane().add(numeroUsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 310, 30));

        emailUsuarioText.setBackground(new java.awt.Color(255, 255, 255));
        emailUsuarioText.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        emailUsuarioText.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(emailUsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 350, 30));

        rgUsuarioText.setBackground(new java.awt.Color(255, 255, 255));
        rgUsuarioText.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        rgUsuarioText.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(rgUsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 310, 30));

        senhaUsuarioText.setBackground(new java.awt.Color(255, 255, 255));
        senhaUsuarioText.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        senhaUsuarioText.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(senhaUsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 310, 30));

        nivelAcessoUsuarioComboBox.setBackground(new java.awt.Color(255, 255, 255));
        nivelAcessoUsuarioComboBox.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(nivelAcessoUsuarioComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 340, 30));

        cadastrarUsuarioBotao.setBackground(new java.awt.Color(51, 0, 51));
        cadastrarUsuarioBotao.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        cadastrarUsuarioBotao.setForeground(new java.awt.Color(255, 153, 255));
        cadastrarUsuarioBotao.setText("CADASTRAR");
        cadastrarUsuarioBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarUsuarioBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarUsuarioBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 580, 50));

        voltarUsuarioBotao.setBackground(new java.awt.Color(51, 0, 51));
        voltarUsuarioBotao.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        voltarUsuarioBotao.setForeground(new java.awt.Color(255, 153, 255));
        voltarUsuarioBotao.setText("VOLTAR");
        voltarUsuarioBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarUsuarioBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(voltarUsuarioBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 70, 20));

        idUsuarioLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        idUsuarioLabel.setForeground(new java.awt.Color(255, 204, 255));
        idUsuarioLabel.setText("Id");
        getContentPane().add(idUsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, 30));

        nomeUsuarioLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        nomeUsuarioLabel.setForeground(new java.awt.Color(255, 204, 255));
        nomeUsuarioLabel.setText("Usuário");
        getContentPane().add(nomeUsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, 30));

        sexoUsuarioLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        sexoUsuarioLabel.setForeground(new java.awt.Color(255, 204, 255));
        sexoUsuarioLabel.setText("Sexo");
        getContentPane().add(sexoUsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, 30));

        dataNascimentoUsuarioLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        dataNascimentoUsuarioLabel.setForeground(new java.awt.Color(255, 204, 255));
        dataNascimentoUsuarioLabel.setText("Data de Nascimento");
        getContentPane().add(dataNascimentoUsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 30));

        numeroUsuarioLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        numeroUsuarioLabel.setForeground(new java.awt.Color(255, 204, 255));
        numeroUsuarioLabel.setText("Número de Telefone");
        getContentPane().add(numeroUsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, 30));

        emailUsuarioLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        emailUsuarioLabel.setForeground(new java.awt.Color(255, 204, 255));
        emailUsuarioLabel.setText("Email");
        getContentPane().add(emailUsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, 30));

        rgUsuarioLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        rgUsuarioLabel.setForeground(new java.awt.Color(255, 204, 255));
        rgUsuarioLabel.setText("Rg");
        getContentPane().add(rgUsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, 30));

        senhaUsuarioLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        senhaUsuarioLabel.setForeground(new java.awt.Color(255, 204, 255));
        senhaUsuarioLabel.setText("Senha");
        getContentPane().add(senhaUsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, 30));

        nivelAcessoUsuarioLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        nivelAcessoUsuarioLabel.setForeground(new java.awt.Color(255, 204, 255));
        nivelAcessoUsuarioLabel.setText("Nível de Acesso");
        getContentPane().add(nivelAcessoUsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, 30));

        telaFundoUsuarioCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Menu+Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(telaFundoUsuarioCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 770, -1));

        telaPrincipalUsuarioCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Mary_kay_Menu.png"))); // NOI18N
        telaPrincipalUsuarioCadastro.setPreferredSize(new java.awt.Dimension(913, 580));
        getContentPane().add(telaPrincipalUsuarioCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeUsuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeUsuarioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeUsuarioTextActionPerformed

    private void numeroUsuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroUsuarioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroUsuarioTextActionPerformed

    private void cadastrarUsuarioBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarUsuarioBotaoActionPerformed
        controller.cadastrarUsuario();

    }//GEN-LAST:event_cadastrarUsuarioBotaoActionPerformed

    private void voltarUsuarioBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarUsuarioBotaoActionPerformed
       controller.voltarParaMenu();
    }//GEN-LAST:event_voltarUsuarioBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarUsuarioBotao;
    private javax.swing.JLabel dataNascimentoUsuarioLabel;
    private javax.swing.JTextField dataUsuarioText;
    private javax.swing.JLabel emailUsuarioLabel;
    private javax.swing.JTextField emailUsuarioText;
    private javax.swing.JLabel idUsuarioLabel;
    private javax.swing.JTextField idUsuarioText;
    private javax.swing.JComboBox<String> nivelAcessoUsuarioComboBox;
    private javax.swing.JLabel nivelAcessoUsuarioLabel;
    private javax.swing.JLabel nomeUsuarioLabel;
    private javax.swing.JTextField nomeUsuarioText;
    private javax.swing.JLabel novoUsuarioLabel;
    private javax.swing.JPanel novoUsuarioPainel;
    private javax.swing.JLabel numeroUsuarioLabel;
    private javax.swing.JTextField numeroUsuarioText;
    private javax.swing.JLabel rgUsuarioLabel;
    private javax.swing.JTextField rgUsuarioText;
    private javax.swing.JLabel senhaUsuarioLabel;
    private javax.swing.JPasswordField senhaUsuarioText;
    private javax.swing.JComboBox<String> sexoUsuarioComboBox;
    private javax.swing.JLabel sexoUsuarioLabel;
    private javax.swing.JLabel telaFundoUsuarioCadastro;
    private javax.swing.JLabel telaPrincipalUsuarioCadastro;
    private javax.swing.JButton voltarUsuarioBotao;
    // End of variables declaration//GEN-END:variables

    public JTextField getDataUsuarioText() {
        return dataUsuarioText;
    }

    public void setDataUsuarioText(JTextField dataUsuarioText) {
        this.dataUsuarioText = dataUsuarioText;
    }

    public JTextField getEmailUsuarioText() {
        return emailUsuarioText;
    }

    public void setEmailUsuarioText(JTextField emailUsuarioText) {
        this.emailUsuarioText = emailUsuarioText;
    }

    public JTextField getIdUsuarioText() {
        return idUsuarioText;
    }

    public void setIdUsuarioText(JTextField idUsuarioText) {
        this.idUsuarioText = idUsuarioText;
    }

    public JComboBox<String> getNivelAcessoUsuarioComboBox() {
        return nivelAcessoUsuarioComboBox;
    }

    public void setNivelAcessoUsuarioComboBox(JComboBox<String> nivelAcessoUsuarioComboBox) {
        this.nivelAcessoUsuarioComboBox = nivelAcessoUsuarioComboBox;
    }

    public JTextField getNomeUsuarioText() {
        return nomeUsuarioText;
    }

    public void setNomeUsuarioText(JTextField nomeUsuarioText) {
        this.nomeUsuarioText = nomeUsuarioText;
    }

    public JTextField getNumeroUsuarioText() {
        return numeroUsuarioText;
    }

    public void setNumeroUsuarioText(JTextField numeroUsuarioText) {
        this.numeroUsuarioText = numeroUsuarioText;
    }

    public JTextField getRgUsuarioText() {
        return rgUsuarioText;
    }

    public void setRgUsuarioText(JTextField rgUsuarioText) {
        this.rgUsuarioText = rgUsuarioText;
    }

    public JPasswordField getSenhaUsuarioText() {
        return senhaUsuarioText;
    }

    public void setSenhaUsuarioText(JPasswordField senhaUsuarioText) {
        this.senhaUsuarioText = senhaUsuarioText;
    }

    public JComboBox<String> getSexoUsuarioComboBox() {
        return sexoUsuarioComboBox;
    }

    public void setSexoUsuarioComboBox(JComboBox<String> sexoUsuarioComboBox) {
        this.sexoUsuarioComboBox = sexoUsuarioComboBox;
    }

    

    
}
