/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Cadastro;

import Controller.Cadastro.CadastroClienteController;
import Model.DAO.Banco;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author tayen
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    private final CadastroClienteController controller;

    public CadastroCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        Banco.inicia();
        controller = new CadastroClienteController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idClienteText = new javax.swing.JTextField();
        nomeClienteText = new javax.swing.JTextField();
        sexoClienteComboBox = new javax.swing.JComboBox<>();
        dataNascClienteText = new javax.swing.JTextField();
        numeroClienteText = new javax.swing.JTextField();
        emailClienteText = new javax.swing.JTextField();
        rgClienteText = new javax.swing.JTextField();
        cepClienteText = new javax.swing.JTextField();
        enderecoClienteText = new javax.swing.JTextField();
        idClienteLabel = new javax.swing.JLabel();
        nomeClienteLabel = new javax.swing.JLabel();
        sexoClienteLabel = new javax.swing.JLabel();
        dataNascClienteLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cadastrarClienteBotao = new javax.swing.JButton();
        voltarClienteBotao = new javax.swing.JButton();
        telaCadastroClienteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idClienteText.setBackground(new java.awt.Color(255, 255, 255));
        idClienteText.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        idClienteText.setForeground(new java.awt.Color(102, 0, 102));
        idClienteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClienteTextActionPerformed(evt);
            }
        });
        getContentPane().add(idClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 160, 40));

        nomeClienteText.setBackground(new java.awt.Color(255, 255, 255));
        nomeClienteText.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        nomeClienteText.setForeground(new java.awt.Color(102, 0, 102));
        nomeClienteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeClienteTextActionPerformed(evt);
            }
        });
        getContentPane().add(nomeClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 370, 40));

        sexoClienteComboBox.setBackground(new java.awt.Color(255, 255, 255));
        sexoClienteComboBox.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        sexoClienteComboBox.setForeground(new java.awt.Color(102, 0, 102));
        sexoClienteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        sexoClienteComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoClienteComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(sexoClienteComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 190, 40));

        dataNascClienteText.setBackground(new java.awt.Color(255, 255, 255));
        dataNascClienteText.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        dataNascClienteText.setForeground(new java.awt.Color(102, 0, 102));
        getContentPane().add(dataNascClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 190, 40));

        numeroClienteText.setBackground(new java.awt.Color(255, 255, 255));
        numeroClienteText.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        numeroClienteText.setForeground(new java.awt.Color(102, 0, 102));
        numeroClienteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroClienteTextActionPerformed(evt);
            }
        });
        getContentPane().add(numeroClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 190, 40));

        emailClienteText.setBackground(new java.awt.Color(255, 255, 255));
        emailClienteText.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        emailClienteText.setForeground(new java.awt.Color(102, 0, 102));
        getContentPane().add(emailClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 240, 40));

        rgClienteText.setBackground(new java.awt.Color(255, 255, 255));
        rgClienteText.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rgClienteText.setForeground(new java.awt.Color(102, 0, 102));
        getContentPane().add(rgClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 190, 40));

        cepClienteText.setBackground(new java.awt.Color(255, 255, 255));
        cepClienteText.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        cepClienteText.setForeground(new java.awt.Color(102, 0, 102));
        getContentPane().add(cepClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 190, 40));

        enderecoClienteText.setBackground(new java.awt.Color(255, 255, 255));
        enderecoClienteText.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        enderecoClienteText.setForeground(new java.awt.Color(102, 0, 102));
        getContentPane().add(enderecoClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 400, 40));

        idClienteLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        idClienteLabel.setForeground(new java.awt.Color(51, 0, 51));
        idClienteLabel.setText("Id");
        getContentPane().add(idClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, 20));

        nomeClienteLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        nomeClienteLabel.setForeground(new java.awt.Color(51, 0, 51));
        nomeClienteLabel.setText("NomeCompleto");
        getContentPane().add(nomeClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, 20));

        sexoClienteLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        sexoClienteLabel.setForeground(new java.awt.Color(51, 0, 51));
        sexoClienteLabel.setText("Sexo");
        getContentPane().add(sexoClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, 20));

        dataNascClienteLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        dataNascClienteLabel.setForeground(new java.awt.Color(51, 0, 51));
        dataNascClienteLabel.setText("Data de Nascimento");
        getContentPane().add(dataNascClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, 20));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Nº Telefone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, 20));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Rg");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, 20));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("CEP");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, 20));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Endereço");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 20));

        cadastrarClienteBotao.setBackground(new java.awt.Color(51, 0, 51));
        cadastrarClienteBotao.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        cadastrarClienteBotao.setForeground(new java.awt.Color(255, 153, 255));
        cadastrarClienteBotao.setText("CADASTRAR");
        cadastrarClienteBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarClienteBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 580, 50));

        voltarClienteBotao.setBackground(new java.awt.Color(51, 0, 51));
        voltarClienteBotao.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        voltarClienteBotao.setForeground(new java.awt.Color(255, 153, 255));
        voltarClienteBotao.setText("VOLTAR");
        voltarClienteBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarClienteBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(voltarClienteBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 20));

        telaCadastroClienteLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Mary_kay_Menu.png"))); // NOI18N
        getContentPane().add(telaCadastroClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idClienteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClienteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idClienteTextActionPerformed

    private void nomeClienteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeClienteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeClienteTextActionPerformed

    private void numeroClienteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroClienteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroClienteTextActionPerformed

    private void cadastrarClienteBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteBotaoActionPerformed
        controller.cadastrarCliente();


    }//GEN-LAST:event_cadastrarClienteBotaoActionPerformed

    private void sexoClienteComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoClienteComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoClienteComboBoxActionPerformed

    private void voltarClienteBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarClienteBotaoActionPerformed
        controller.voltarParaMenu();
    }//GEN-LAST:event_voltarClienteBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarClienteBotao;
    private javax.swing.JTextField cepClienteText;
    private javax.swing.JLabel dataNascClienteLabel;
    private javax.swing.JTextField dataNascClienteText;
    private javax.swing.JTextField emailClienteText;
    private javax.swing.JTextField enderecoClienteText;
    private javax.swing.JLabel idClienteLabel;
    private javax.swing.JTextField idClienteText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel nomeClienteLabel;
    private javax.swing.JTextField nomeClienteText;
    private javax.swing.JTextField numeroClienteText;
    private javax.swing.JTextField rgClienteText;
    private javax.swing.JComboBox<String> sexoClienteComboBox;
    private javax.swing.JLabel sexoClienteLabel;
    private javax.swing.JLabel telaCadastroClienteLabel;
    private javax.swing.JButton voltarClienteBotao;
    // End of variables declaration//GEN-END:variables

    public JTextField getCepClienteText() {
        return cepClienteText;
    }

    public void setCepClienteText(JTextField cepClienteText) {
        this.cepClienteText = cepClienteText;
    }

    public JTextField getDataNascClienteText() {
        return dataNascClienteText;
    }

    public void setDataNascClienteText(JTextField dataNascClienteText) {
        this.dataNascClienteText = dataNascClienteText;
    }

    public JTextField getEmailClienteText() {
        return emailClienteText;
    }

    public void setEmailClienteText(JTextField emailClienteText) {
        this.emailClienteText = emailClienteText;
    }

    public JTextField getEnderecoClienteText() {
        return enderecoClienteText;
    }

    public void setEnderecoClienteText(JTextField enderecoClienteText) {
        this.enderecoClienteText = enderecoClienteText;
    }

    public JTextField getIdClienteText() {
        return idClienteText;
    }

    public void setIdClienteText(JTextField idClienteText) {
        this.idClienteText = idClienteText;
    }

    public JTextField getNomeClienteText() {
        return nomeClienteText;
    }

    public void setNomeClienteText(JTextField nomeClienteText) {
        this.nomeClienteText = nomeClienteText;
    }

    public JTextField getNumeroClienteText() {
        return numeroClienteText;
    }

    public void setNumeroClienteText(JTextField numeroClienteText) {
        this.numeroClienteText = numeroClienteText;
    }

    public JTextField getRgClienteText() {
        return rgClienteText;
    }

    public void setRgClienteText(JTextField rgClienteText) {
        this.rgClienteText = rgClienteText;
    }

    public JComboBox<String> getSexoClienteComboBox() {
        return sexoClienteComboBox;
    }

    public void setSexoClienteComboBox(JComboBox<String> sexoClienteComboBox) {
        this.sexoClienteComboBox = sexoClienteComboBox;
    }

}
