/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AgendaController;
import Model.DAO.Banco;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author tayen
 */
public class Agenda extends javax.swing.JFrame {

    private final AgendaController controller;

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        controller = new AgendaController(this);
        Banco.inicia();
        iniciar();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        IdLabel = new javax.swing.JLabel();
        ClienteLabel = new javax.swing.JLabel();
        ServicoLabel = new javax.swing.JLabel();
        ValorLabel = new javax.swing.JLabel();
        DataLabel = new javax.swing.JLabel();
        HoraLabel = new javax.swing.JLabel();
        ObservacoesLabel = new javax.swing.JLabel();
        BotaoAgendar = new javax.swing.JButton();
        IdCampo = new javax.swing.JTextField();
        ClienteComboBox = new javax.swing.JComboBox<>();
        ServicoComboBox = new javax.swing.JComboBox<>();
        ValorCampo = new javax.swing.JTextField();
        DataCampo = new javax.swing.JTextField();
        HoraCampo = new javax.swing.JTextField();
        ObservacoesPane = new javax.swing.JScrollPane();
        ObservacoesCampo = new javax.swing.JTextArea();
        AgendaFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabela.setBackground(new java.awt.Color(255, 255, 255));
        Tabela.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        Tabela.setForeground(new java.awt.Color(204, 0, 0));
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observações"
            }
        ));
        Tabela.setGridColor(new java.awt.Color(204, 0, 0));
        Tabela.setSelectionBackground(new java.awt.Color(255, 204, 204));
        Tabela.setSelectionForeground(new java.awt.Color(204, 0, 0));
        jScrollPane1.setViewportView(Tabela);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 820, 180));

        IdLabel.setBackground(new java.awt.Color(255, 255, 255));
        IdLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        IdLabel.setForeground(new java.awt.Color(204, 0, 0));
        IdLabel.setText("Id");
        getContentPane().add(IdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, 30));

        ClienteLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ClienteLabel.setForeground(new java.awt.Color(204, 0, 0));
        ClienteLabel.setText("Cliente");
        getContentPane().add(ClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 30));

        ServicoLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ServicoLabel.setForeground(new java.awt.Color(204, 0, 0));
        ServicoLabel.setText("Serviço");
        getContentPane().add(ServicoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 30));

        ValorLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ValorLabel.setForeground(new java.awt.Color(204, 0, 0));
        ValorLabel.setText("Valor");
        getContentPane().add(ValorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, 30));

        DataLabel.setBackground(new java.awt.Color(255, 102, 102));
        DataLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        DataLabel.setForeground(new java.awt.Color(204, 0, 0));
        DataLabel.setText("Hora");
        getContentPane().add(DataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, 30));

        HoraLabel.setBackground(new java.awt.Color(255, 102, 102));
        HoraLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        HoraLabel.setForeground(new java.awt.Color(204, 0, 0));
        HoraLabel.setText("Data");
        getContentPane().add(HoraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 30));

        ObservacoesLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ObservacoesLabel.setForeground(new java.awt.Color(204, 0, 0));
        ObservacoesLabel.setText("Observações");
        getContentPane().add(ObservacoesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, -1, 30));

        BotaoAgendar.setBackground(new java.awt.Color(204, 0, 0));
        BotaoAgendar.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        BotaoAgendar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoAgendar.setText("AGENDAR");
        BotaoAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 490, 50));

        IdCampo.setBackground(new java.awt.Color(255, 255, 255));
        IdCampo.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        IdCampo.setForeground(new java.awt.Color(204, 0, 0));
        IdCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdCampoActionPerformed(evt);
            }
        });
        getContentPane().add(IdCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 410, 30));

        ClienteComboBox.setBackground(new java.awt.Color(255, 255, 255));
        ClienteComboBox.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        ClienteComboBox.setForeground(new java.awt.Color(204, 0, 0));
        ClienteComboBox.setBorder(null);
        ClienteComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ClienteComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 410, 30));

        ServicoComboBox.setBackground(new java.awt.Color(255, 255, 255));
        ServicoComboBox.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        ServicoComboBox.setForeground(new java.awt.Color(204, 0, 0));
        ServicoComboBox.setBorder(null);
        ServicoComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ServicoComboBoxItemStateChanged(evt);
            }
        });
        getContentPane().add(ServicoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 410, 30));

        ValorCampo.setBackground(new java.awt.Color(255, 255, 255));
        ValorCampo.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ValorCampo.setForeground(new java.awt.Color(204, 0, 0));
        ValorCampo.setEnabled(false);
        ValorCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorCampoActionPerformed(evt);
            }
        });
        getContentPane().add(ValorCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 410, 30));

        DataCampo.setBackground(new java.awt.Color(255, 255, 255));
        DataCampo.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        DataCampo.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(DataCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 410, 30));

        HoraCampo.setBackground(new java.awt.Color(255, 255, 255));
        HoraCampo.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        HoraCampo.setForeground(new java.awt.Color(204, 0, 0));
        HoraCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraCampoActionPerformed(evt);
            }
        });
        getContentPane().add(HoraCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 410, 30));

        ObservacoesPane.setBackground(new java.awt.Color(255, 255, 255));
        ObservacoesPane.setForeground(new java.awt.Color(204, 0, 0));

        ObservacoesCampo.setBackground(new java.awt.Color(255, 255, 255));
        ObservacoesCampo.setColumns(20);
        ObservacoesCampo.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        ObservacoesCampo.setForeground(new java.awt.Color(204, 0, 0));
        ObservacoesCampo.setRows(5);
        ObservacoesPane.setViewportView(ObservacoesCampo);

        getContentPane().add(ObservacoesPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 490, 280));

        AgendaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/AgendaMK.jpg"))); // NOI18N
        getContentPane().add(AgendaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdCampoActionPerformed

    private void ClienteComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteComboBoxActionPerformed
                
    }//GEN-LAST:event_ClienteComboBoxActionPerformed

    private void BotaoAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAgendarActionPerformed
        
       this.controller.agendar();
        
    }//GEN-LAST:event_BotaoAgendarActionPerformed

    private void HoraCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraCampoActionPerformed

    private void ServicoComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ServicoComboBoxItemStateChanged
              controller.atualizaValor();
    }//GEN-LAST:event_ServicoComboBoxItemStateChanged

    private void ValorCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorCampoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgendaFundo;
    private javax.swing.JButton BotaoAgendar;
    private javax.swing.JComboBox<String> ClienteComboBox;
    private javax.swing.JLabel ClienteLabel;
    private javax.swing.JTextField DataCampo;
    private javax.swing.JLabel DataLabel;
    private javax.swing.JTextField HoraCampo;
    private javax.swing.JLabel HoraLabel;
    private javax.swing.JTextField IdCampo;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JTextArea ObservacoesCampo;
    private javax.swing.JLabel ObservacoesLabel;
    private javax.swing.JScrollPane ObservacoesPane;
    private javax.swing.JComboBox<String> ServicoComboBox;
    private javax.swing.JLabel ServicoLabel;
    private javax.swing.JTable Tabela;
    private javax.swing.JTextField ValorCampo;
    private javax.swing.JLabel ValorLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        
        controller.atualizaTabela();
        controller.atualizaCliente();
        controller.atualizaServico();
        controller.atualizaValor();
        

    }

    public JTable getTabela() {
        return Tabela;
    }

    public void setTabela(JTable Tabela) {
        this.Tabela = Tabela;
    }

    public JComboBox<String> getClienteComboBox() {
        return ClienteComboBox;
    }

    public void setClienteComboBox(JComboBox<String> ClienteComboBox) {
        this.ClienteComboBox = ClienteComboBox;
    }

    public JComboBox<String> getServicoComboBox() {
        return ServicoComboBox;
    }

    public void setServicoComboBox(JComboBox<String> ServicoComboBox) {
        this.ServicoComboBox = ServicoComboBox;
    }

    public JTextField getDataCampo() {
        return DataCampo;
    }

    public void setDataCampo(JTextField DataCampo) {
        this.DataCampo = DataCampo;
    }

    public JTextField getHoraCampo() {
        return HoraCampo;
    }

    public void setHoraCampo(JTextField HoraCampo) {
        this.HoraCampo = HoraCampo;
    }

    public JTextField getIdCampo() {
        return IdCampo;
    }

    public void setIdCampo(JTextField IdCampo) {
        this.IdCampo = IdCampo;
    }

    public JTextField getValorCampo() {
        return ValorCampo;
    }

    public void setValorCampo(JTextField ValorCampo) {
        this.ValorCampo = ValorCampo;
    }

    public JTextArea getObservacoesCampo() {
        return ObservacoesCampo;
    }

    public void setObservacoesCampo(JTextArea ObservacoesCampo) {
        this.ObservacoesCampo = ObservacoesCampo;
    }
    
    
    
    
}
