/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoginController;
import Model.DAO.Banco;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author tayen
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
         this.setLocationRelativeTo(null);
        Banco.inicia();
        
        controller = new LoginController(this);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Entrar = new javax.swing.JButton();
        login_label = new javax.swing.JLabel();
        Senha_text = new javax.swing.JPasswordField();
        usuario_Text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuário");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 211, -1, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 60, 30));

        Entrar.setBackground(new java.awt.Color(34, 0, 34));
        Entrar.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        Entrar.setForeground(new java.awt.Color(255, 255, 255));
        Entrar.setText("ENTRAR");
        Entrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 3, true));
        Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        Entrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EntrarKeyPressed(evt);
            }
        });
        getContentPane().add(Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));

        login_label.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        login_label.setForeground(new java.awt.Color(255, 255, 255));
        login_label.setText("LOGIN");
        login_label.setToolTipText("");
        getContentPane().add(login_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        Senha_text.setBackground(new java.awt.Color(255, 153, 255));
        Senha_text.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Senha_text.setForeground(new java.awt.Color(51, 0, 51));
        Senha_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Senha_textActionPerformed(evt);
            }
        });
        getContentPane().add(Senha_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 450, 50));

        usuario_Text.setBackground(new java.awt.Color(255, 153, 255));
        usuario_Text.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        usuario_Text.setForeground(new java.awt.Color(51, 0, 51));
        usuario_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario_TextActionPerformed(evt);
            }
        });
        getContentPane().add(usuario_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 450, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/mary_kay_painel.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuario_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario_TextActionPerformed

    private void Senha_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Senha_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Senha_textActionPerformed

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        try {
            // Quando clico no botão entrar
            this.controller.entrarSistema();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_EntrarActionPerformed

    private void EntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntrarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JPasswordField Senha_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel login_label;
    private javax.swing.JTextField usuario_Text;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {

        JOptionPane.showMessageDialog(null, mensagem);

    }

    public JPasswordField getSenha_text() {
        return Senha_text;
    }

    public void setSenha_text(JPasswordField Senha_text) {
        this.Senha_text = Senha_text;
    }

    public JTextField getUsuario_Text() {
        return usuario_Text;
    }

    public void setUsuario_Text(JTextField usuario_Text) {
        this.usuario_Text = usuario_Text;
    }
    
}
