/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MenuController;
import Model.DAO.Banco;
import Model.Usuario;
import View.Cadastro.CadastroUsuario;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author tayen
 */
public class Menu extends javax.swing.JFrame {

    private final MenuController controller;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);

        controller = new MenuController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltarParaTelaDeLogin = new javax.swing.JButton();
        MenuPanel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemServico = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        JMenuOperacao = new javax.swing.JMenu();
        jMenuItemAgenda = new javax.swing.JMenuItem();
        JMenuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();
        jMenuItemFeedback = new javax.swing.JMenuItem();
        jMenuItemDicas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaption);
        setForeground(new java.awt.Color(255, 51, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltarParaTelaDeLogin.setBackground(new java.awt.Color(51, 0, 51));
        voltarParaTelaDeLogin.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        voltarParaTelaDeLogin.setForeground(new java.awt.Color(255, 153, 255));
        voltarParaTelaDeLogin.setText("ALTERNAR USUÁRIO");
        voltarParaTelaDeLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarParaTelaDeLoginActionPerformed(evt);
            }
        });
        getContentPane().add(voltarParaTelaDeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 240, 20));

        MenuPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Mary_kay_Menu.png"))); // NOI18N
        getContentPane().add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(51, 0, 51));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(51, 0, 51));
        jMenuBar1.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N

        jMenuCadastro.setBackground(new java.awt.Color(255, 155, 255));
        jMenuCadastro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuCadastro.setForeground(new java.awt.Color(51, 0, 51));
        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        jMenuItemCliente.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemCliente.setForeground(new java.awt.Color(153, 0, 153));
        jMenuItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Cadastro.Cliente.png"))); // NOI18N
        jMenuItemCliente.setText("Cliente");
        jMenuItemCliente.setEnabled(false);
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCliente);

        jMenuItemServico.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemServico.setForeground(new java.awt.Color(153, 0, 153));
        jMenuItemServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Cadastro.Servico.png"))); // NOI18N
        jMenuItemServico.setText("Serviço");
        jMenuItemServico.setEnabled(false);
        jMenuItemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemServicoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemServico);

        jMenuItemUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemUsuario.setForeground(new java.awt.Color(153, 0, 153));
        jMenuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Cadastro.Usuario.png"))); // NOI18N
        jMenuItemUsuario.setText("Usuário");
        jMenuItemUsuario.setEnabled(false);
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemUsuario);

        jMenuBar1.add(jMenuCadastro);

        JMenuOperacao.setBackground(new java.awt.Color(255, 162, 255));
        JMenuOperacao.setForeground(new java.awt.Color(51, 0, 51));
        JMenuOperacao.setText("Operação");
        JMenuOperacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JMenuOperacao.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        jMenuItemAgenda.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemAgenda.setForeground(new java.awt.Color(153, 0, 153));
        jMenuItemAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Operacao.Agenda.png"))); // NOI18N
        jMenuItemAgenda.setText("Agenda");
        jMenuItemAgenda.setEnabled(false);
        jMenuItemAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendaActionPerformed(evt);
            }
        });
        JMenuOperacao.add(jMenuItemAgenda);

        jMenuBar1.add(JMenuOperacao);

        JMenuAjuda.setBackground(new java.awt.Color(255, 162, 255));
        JMenuAjuda.setForeground(new java.awt.Color(51, 0, 51));
        JMenuAjuda.setText("Ajuda");
        JMenuAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JMenuAjuda.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        jMenuItemSobre.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemSobre.setForeground(new java.awt.Color(153, 0, 153));
        jMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Cadastro.Cliente.png"))); // NOI18N
        jMenuItemSobre.setText("Sobre mim");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        JMenuAjuda.add(jMenuItemSobre);

        jMenuItemFeedback.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemFeedback.setForeground(new java.awt.Color(153, 0, 153));
        jMenuItemFeedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Cadastro.Servico.png"))); // NOI18N
        jMenuItemFeedback.setText("Dê seu Feedback");
        jMenuItemFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFeedbackActionPerformed(evt);
            }
        });
        JMenuAjuda.add(jMenuItemFeedback);

        jMenuItemDicas.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemDicas.setForeground(new java.awt.Color(153, 0, 153));
        jMenuItemDicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Cadastro.Usuario.png"))); // NOI18N
        jMenuItemDicas.setText("Dicas");
        jMenuItemDicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDicasActionPerformed(evt);
            }
        });
        JMenuAjuda.add(jMenuItemDicas);

        jMenuBar1.add(JMenuAjuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed

       
        this.controller.entrarCadastroCliente();
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendaActionPerformed

        this.controller.entrarAgenda();

    }//GEN-LAST:event_jMenuItemAgendaActionPerformed

    private void jMenuItemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServicoActionPerformed
        this.controller.entrarCadastroServico();
    }//GEN-LAST:event_jMenuItemServicoActionPerformed

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
           this.controller.entrarCadastroUsuario();
           
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void voltarParaTelaDeLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarParaTelaDeLoginActionPerformed
        controller.voltarParaTelaDeLogin();
    }//GEN-LAST:event_voltarParaTelaDeLoginActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFeedbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFeedbackActionPerformed

    private void jMenuItemDicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDicasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDicasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuAjuda;
    private javax.swing.JMenu JMenuOperacao;
    private javax.swing.JLabel MenuPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemAgenda;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemDicas;
    private javax.swing.JMenuItem jMenuItemFeedback;
    private javax.swing.JMenuItem jMenuItemServico;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JButton voltarParaTelaDeLogin;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getjMenuItemCliente() {
        return jMenuItemCliente;
    }

    public void setjMenuItemCliente(JMenuItem jMenuItemCliente) {
        this.jMenuItemCliente = jMenuItemCliente;
    }

    public JMenuItem getjMenuItemServico() {
        return jMenuItemServico;
    }

    public void setjMenuItemServico(JMenuItem jMenuItemServico) {
        this.jMenuItemServico = jMenuItemServico;
    }

    public JMenuItem getjMenuItemUsuario() {
        return jMenuItemUsuario;
    }

    public void setjMenuItemUsuario(JMenuItem jMenuItemUsuario) {
        this.jMenuItemUsuario = jMenuItemUsuario;
    }

}
